language: python
python:
  - "3.5"
install: "python setup.py install"
# before_script:
#   - cp .env.example .env
#   - python manage.py migrate
script:
  - flake8 cmdbox
  - coverage run manage.py test --settings=cmdbox.tests_settings
after_success:
  - coveralls
