@startuml PredictInfrared
' Endpoint: /predict/infrared [POST]
' Endpoint: /api/v1/chemspectra/predict/infrared [POST]

actor       User
boundary    InferenceAPI
control     InferenceHandler
entity      MoleculeModel
control     InferModel
boundary    InferIR

User -> InferenceAPI
InferenceAPI -> InferenceHandler
InferenceHandler -> MoleculeModel: get molecule model
MoleculeModel --> InferenceHandler: molecule model
InferenceHandler -> InferModel: predict infrared
InferModel -> InferIR: predict infrared
InferIR --> InferModel: predicted values, error

alt has error
    InferModel --> InferenceHandler: error
    InferenceHandler --> InferenceAPI: Error 400
    InferenceAPI --> User: Error 400
else
    InferModel --> InferenceHandler: predicted data
    InferenceHandler --> InferenceAPI: predicted data
    InferenceAPI --> User: predicted data
end
    

@enduml