FROM python:3.12-slim AS base

# Install any additional OS packages you want in addition to sudo, git and nano
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo git nano \
# required 
    gcc g++ libxrender1 libxext6 libglib2.0-0

ARG USERNAME=debian

# add default user with no password and sudo privilege
RUN useradd -m --shell /bin/bash $USERNAME && passwd -d ${USERNAME} && adduser ${USERNAME} sudo

USER $USERNAME
WORKDIR /home/${USERNAME}

ENV PIP_CACHE_DIR=./.cache/pip
ENV PIP_USER=1
ENV PIP_NO_WARN_SCRIPT_LOCATION=1

RUN mkdir -p ${PIP_CACHE_DIR}

# to be replaced later by ADD git#branch if needed
COPY pyproject.toml .

RUN --mount=type=cache,target=${PIP_CACHE_DIR},sharing=locked,id=pip-cache \
    touch README.md && pip install --upgrade pip && pip install .[dev] && rm -rf README.md pyproject.toml build *.egg-info
